server:
  port: 8087
  error:
    include:
      message: true

grpc:
  server:
    port: 8092
  client:
    grpcUsersClient:
      address: 'static://localhost:8093'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://localhost:8094'
      negotiationType: PLAINTEXT

spring:
  application:
    name: rangiffler-photo
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rangiffler-photo'
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG